#【選擇插件運作語言】
#目前僅支援：
#zh_TW: 繁體中文
#zh_CN: 簡體中文
language: "zh_TW"
#【使用自己修改過的語系檔案】
useModifiedLanguage: false

#【插件前綴】
# 使用聲明：
# 更改插件前綴是為各位服主在訊息辨別上更加方便，
# 但更改此前綴並不代表你可以聲明MQ為你的自製插件，
# MQ一直以來的精神為不收費與開源，作者開放此設定也是經過良久考慮，
# 請大家對插件有基本的尊重，感謝配合。
pluginPrefix: "&6MangoQuest>"

#【除錯模式】
# 沒事不要亂開，小黑窗會悲劇。 
debug: false


#【是否右鍵NPC開啟對話選單】
#關掉就只能使用指令來接任務。
useRightClickMenu: true

#【玩家最大任務數量】
maxQuestAmount: 4

#【登入時傳送讀取完成訊息】
popLoginMessage: true

#【是否啟用記分板系統】
enableScoreboard: true

#【記分板上可接受的任務之顯示數量】
scoreboardMaxCanTakeQuestAmount: 3

#【使用NPC效果】
useParticleEffect: true
